[SAPI]
# The main URL to fetch the package list from
INDEX_URL = https://sapi.suse.com/beta/simple/index.html
# The base URL for pip install --index-url
BASE_INDEX_URL = https://sapi.suse.com/beta/simple

[DOCKER]
# The container image to use for testing
IMAGE = registry.suse.com/bci/python:3.11
# The platform architecture to emulate/use
PLATFORM = linux/amd64

[REPORTING]
# Directory to store JSON and Markdown reports
DIR = reports
